import { Product } from "@/types/product";

export const products: Product[] = [
  {
    id: "prod-1",
    slug: "aegis-pp-automatic",
    name: "Aegis-Band PP — Automatic Machine Grade",
    brand: "Aegis-Band",
    categorySlug: "pp-strapping",
    categoryName: "Polypropylene (PP) Strapping",
    machineType: "Full Automatic",
    tagline: "Ultra-pure virgin polypropylene band tailored for continuous high-speed arch cycles without dust or camber curving.",
    summary:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. High tensile strength with consistent split-free embossing, guaranteeing smooth track travel in 60+ cycle/min automated lines.",
    description: [
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi pellentesque euismod venenatis. Nulla facilisi. Proin id libero id nisi pretium consequat sit amet vel magna.",
      "Manufactured exclusively from 100% prime virgin polypropylene homopolymer resins. Every batch undergoes automated laser micrometer inspection for gauge consistency and minimal camber variance, virtually eliminating arch misfeeds and strap jams.",
      "Suitable for high-throughput corrugated box plants, carton printing houses, pharmaceutical cartoning, and commercial printing operations.",
    ],
    features: [
      "Zero camber curving (< 15mm per 2m) ensuring smooth arch flight",
      "High tensile break strength up to 280 kgf with optimal elasticity",
      "Diamond-cut embossing for consistent drive roller traction and joint welding",
      "Compatible with all European, Japanese, and Taiwanese automatic arch machinery",
      "Standard 200mm (8-inch) core diameter with moisture-resistant flange packaging",
    ],
    specifications: [
      { label: "Material Composition", value: "100% Virgin Polypropylene (PP)" },
      { label: "Available Widths", value: "5mm, 6mm, 9mm, 12mm, 15mm" },
      { label: "Thickness Range", value: "0.55mm – 0.85mm (±0.03mm)" },
      { label: "Coil Length", value: "2,000m – 7,000m per coil" },
      { label: "Average Break Strength", value: "110 kgf – 290 kgf" },
      { label: "Elongation at Break", value: "15% – 20%" },
      { label: "Core Inner Diameter", value: "200mm (8 inches)" },
      { label: "Standard Color", value: "Translucent White, Clear, Blue, Yellow" },
      { label: "Surface Finish", value: "Fine Diamond Embossed or Smooth" },
    ],
    packagingDetails: {
      coilsPerPallet: "40 coils / pallet",
      coreDiameter: "200 mm",
      palletWeight: "480 kg gross",
    },
    imageType: "coil-pp",
    isFeatured: true,
    relatedSlugs: ["aegis-pp-semi-automatic", "aegis-auto-pro-arch-8060", "aegis-pet-heavy-duty"],
    inquiryPreset: "Inquiry regarding Aegis-Band PP Automatic Machine Grade",
  },
  {
    id: "prod-2",
    slug: "aegis-pp-semi-automatic",
    name: "Aegis-Band PP — Semi-Automatic Table Grade",
    brand: "Aegis-Band",
    categorySlug: "pp-strapping",
    categoryName: "Polypropylene (PP) Strapping",
    machineType: "Semi Automatic",
    tagline: "Economical and flexible PP strapping formulated for open-table semi-automatic strapping machines.",
    summary:
      "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore. Reliable thermal adhesion with high split resistance for multi-operator packing stations.",
    description: [
      "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.",
      "Optimized for tabletop semi-automatic packaging machines where manual package positioning is required. Its balanced rigidity allows easy feeding through the guide slot without curling or snagging.",
      "Ideal for general warehousing, e-commerce fulfillment hubs, spare parts distribution, and garment packaging.",
    ],
    features: [
      "Flexible yet rigid strap body for effortless feeding into table slots",
      "Immediate heater-blade weld formation with high joint efficiency (>75%)",
      "Low dust accumulation to extend heating blade and roller service life",
      "Available in multiple colors for department sorting and inventory batching",
    ],
    specifications: [
      { label: "Material Composition", value: "Virgin Polypropylene + Copolymer Impact Modifiers" },
      { label: "Available Widths", value: "9mm, 12mm, 15mm" },
      { label: "Thickness Range", value: "0.60mm – 0.80mm" },
      { label: "Coil Length", value: "2,500m – 3,500m per coil" },
      { label: "Average Break Strength", value: "120 kgf – 210 kgf" },
      { label: "Core Inner Diameter", value: "200mm (8 inches)" },
      { label: "Standard Color", value: "Yellow, Blue, Black, White" },
    ],
    packagingDetails: {
      coilsPerPallet: "48 coils / pallet",
      coreDiameter: "200 mm",
      palletWeight: "520 kg gross",
    },
    imageType: "coil-pp",
    isFeatured: true,
    relatedSlugs: ["aegis-pp-automatic", "aegis-table-semi-740", "aegis-cart-mobile-dispenser"],
    inquiryPreset: "Inquiry regarding Aegis-Band PP Semi-Automatic Table Grade",
  },
  {
    id: "prod-3",
    slug: "aegis-pp-manual-grade",
    name: "Aegis-Band PP — Manual Hand Grade",
    brand: "Aegis-Band",
    categorySlug: "pp-strapping",
    categoryName: "Polypropylene (PP) Strapping",
    machineType: "Manual / Hand Tools",
    tagline: "Cost-effective heavy-gauge strapping coiled for manual tensioners and metal crimp seals.",
    summary:
      "Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip. Thickened gauge engineered for high ratchet tensioning and serrated metal seal grip.",
    description: [
      "Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit.",
      "Engineered specifically for low-volume or outdoor dispatch yards where electricity is not available. Paired with manual ratcheting tensioners and steel seals for dependable cargo stabilization.",
    ],
    features: [
      "High lateral tear resistance against sharp-cornered wooden crates",
      "Deep diamond knurling for maximal seal friction grip",
      "Packaged in self-dispensing tote boxes or standard wooden core rolls",
    ],
    specifications: [
      { label: "Material Composition", value: "High-Molecular-Weight Polypropylene" },
      { label: "Available Widths", value: "12mm, 15mm, 18mm" },
      { label: "Thickness Range", value: "0.80mm – 1.00mm" },
      { label: "Coil Length", value: "1,000m – 1,500m per coil" },
      { label: "Average Break Strength", value: "190 kgf – 320 kgf" },
      { label: "Joint Compatibility", value: "Serrated Metal Seals / Wire Buckles" },
    ],
    imageType: "coil-pp",
    isFeatured: false,
    relatedSlugs: ["aegis-tool-manual-kit", "aegis-cart-mobile-dispenser"],
    inquiryPreset: "Inquiry regarding Aegis-Band PP Manual Hand Grade",
  },
  {
    id: "prod-4",
    slug: "aegis-pet-heavy-duty",
    name: "Aegis-Tough PET — Industrial High-Tensile Band",
    brand: "Aegis-Tough",
    categorySlug: "pet-strapping",
    categoryName: "Polyester (PET) Strapping Band",
    machineType: "Full Automatic",
    tagline: "The proven modern alternative to steel strapping for heavy palletization, brick packs, and metals.",
    summary:
      "Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia. High retained tension, weather impervious, and zero safety risk from snapping steel edges.",
    description: [
      "Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Praesent libero. Sed cursus ante dapibus diam.",
      "Aegis-Tough Polyester (PET) band combines the strength of steel strapping with the elasticity and shock absorption of plastics. Unlike steel, it does not rust, leave stains on finished surfaces, or whip back dangerously when cut.",
      "Widely deployed in lumber yards, ceramic tile manufacturing, glass transport, and automated pallet wrapping cells.",
    ],
    features: [
      "High retained tension: retains clamping force even if pallets settle during transit",
      "Zero corrosion: completely immune to rain, humidity, and UV exposure",
      "Up to 50% cost savings compared to traditional heavy-duty steel bands",
      "Superior elongation recovery absorbs transport shocks and road vibrations",
    ],
    specifications: [
      { label: "Material Composition", value: "Oriented Polyethylene Terephthalate (PET)" },
      { label: "Available Widths", value: "12mm, 15.5mm, 19mm, 25mm" },
      { label: "Thickness Range", value: "0.60mm – 1.20mm" },
      { label: "Coil Length", value: "1,000m – 2,500m per coil" },
      { label: "Average Break Strength", value: "450 kgf – 1,200 kgf" },
      { label: "Elongation Elastic Recovery", value: "6% – 12% dynamic recovery" },
      { label: "Core Inner Diameter", value: "406mm (16 inches) heavy industry core" },
      { label: "Color", value: "Gloss Green / Jet Black" },
      { label: "Surface Finish", value: "Embossed or Waxed Smooth" },
    ],
    packagingDetails: {
      coilsPerPallet: "28 coils / pallet",
      coreDiameter: "406 mm",
      palletWeight: "650 kg gross",
    },
    imageType: "coil-pet",
    isFeatured: true,
    relatedSlugs: ["aegis-pet-extreme-tensile", "aegis-power-batt-1600", "aegis-air-pneumatic-sealer"],
    inquiryPreset: "Inquiry regarding Aegis-Tough PET Industrial High-Tensile Band",
  },
  {
    id: "prod-5",
    slug: "aegis-pet-extreme-tensile",
    name: "Aegis-Tough PET — Extreme Heavy Load Series",
    brand: "Aegis-Tough",
    categorySlug: "pet-strapping",
    categoryName: "Polyester (PET) Strapping Band",
    machineType: "Full Automatic",
    tagline: "Extra-thick oriented polyester strap engineered to bundle raw timber, structural steel, and export containers.",
    summary:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Up to 1,500 kgf tensile resistance with high joint friction weld compatibility.",
    description: [
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum.",
      "Engineered for brutal industrial environments where load shifting represents a severe safety hazard. With exceptional split resistance and high-retained tension, this band securely immobilizes heavy coils, pipes, and bulk pallets.",
    ],
    features: [
      "Extreme tensile rating exceeding 1,450 kgf break load",
      "High shock-absorbency prevents strap snapping during vessel roll and transit shocks",
      "Protects delicate edges from cut damage compared to razor-sharp steel strapping",
    ],
    specifications: [
      { label: "Material Composition", value: "High-Viscosity Virgin PET" },
      { label: "Available Widths", value: "19mm, 25mm, 32mm" },
      { label: "Thickness Range", value: "1.00mm – 1.40mm" },
      { label: "Coil Length", value: "900m – 1,400m per coil" },
      { label: "Break Strength", value: "850 kgf – 1,550 kgf" },
      { label: "Core Inner Diameter", value: "406mm (16 inches)" },
      { label: "Standard Color", value: "Dark Bottle Green" },
    ],
    imageType: "coil-pet",
    isFeatured: false,
    relatedSlugs: ["aegis-pet-heavy-duty", "aegis-air-pneumatic-sealer", "aegis-power-batt-1600"],
    inquiryPreset: "Inquiry regarding Aegis-Tough PET Extreme Heavy Load Series",
  },
  {
    id: "prod-6",
    slug: "aegis-auto-pro-arch-8060",
    name: "Aegis-Auto Pro Arch 8060 Strapping Machine",
    brand: "Aegis-Machinery",
    categorySlug: "strapping-machines",
    categoryName: "Industrial Strapping Machinery",
    machineType: "Full Automatic",
    tagline: "High-speed automated arch strapping unit delivering 65 straps per minute with brushless servo drive.",
    summary:
      "Praesent mauris. Fusce nec tellus sed augue semper porta. Continuous automated arch bundling with auto-strap re-feed and auto-loop ejector technology.",
    description: [
      "Praesent mauris. Fusce nec tellus sed augue semper porta. Mauris massa. Vestibulum lacinia arcu eget nulla. Class aptent taciti sociosqu.",
      "Designed for demanding industrial packaging lines that operate 24/7. Equipped with brushless direct-drive German servomotors, the unit contains 30% fewer moving parts than traditional clutch-driven machines, dramatically reducing maintenance downtime.",
      "Features intelligent electronic tension control, auto-refeed in case of strap misfeeding, and a safety interlock hood.",
    ],
    features: [
      "Blazing throughput: Up to 65 straps/minute cycle speed",
      "Direct Drive German servo motors eliminating mechanical belts and clutches",
      "Automatic loop ejector prevents jams in dry-run cycles",
      "Instant electronic heater temperature stabilization",
      "Stainless steel roller top with adjustable table height",
    ],
    specifications: [
      { label: "Arch Dimensions", value: "Standard 850mm (W) x 600mm (H) (Custom arches available)" },
      { label: "Strapping Speed", value: "Up to 65 straps / min" },
      { label: "Strap Width Range", value: "5mm, 6mm, 9mm, 12mm" },
      { label: "Tension Range", value: "10 kgf – 70 kgf electronic variable" },
      { label: "Power Supply", value: "220V / 50Hz, 1-Phase or 380V 3-Phase" },
      { label: "Machine Dimensions", value: "1,440mm (L) x 640mm (W) x 1,510mm (H)" },
      { label: "Total Net Weight", value: "185 kg" },
    ],
    imageType: "machine-auto",
    isFeatured: true,
    relatedSlugs: ["aegis-pp-automatic", "aegis-table-semi-740"],
    inquiryPreset: "Inquiry regarding Aegis-Auto Pro Arch 8060 Strapping Machine",
  },
  {
    id: "prod-7",
    slug: "aegis-table-semi-740",
    name: "Aegis-Table Semi 740 Semi-Automatic Machine",
    brand: "Aegis-Machinery",
    categorySlug: "strapping-machines",
    categoryName: "Industrial Strapping Machinery",
    machineType: "Semi Automatic",
    tagline: "Reliable open-cabinet semi-automatic strapping table with quiet DC motors and external tension dial.",
    summary:
      "Curabitur sodales ligula in libero. Sed dignissim lacinia nunc. Simple 1.5-second strap cycle for versatile carton bundling and irregular parcel wrapping.",
    description: [
      "Curabitur sodales ligula in libero. Sed dignissim lacinia nunc. Curabitur tortor. Pellentesque nibh. Aenean quam.",
      "The benchmark workhorse for small-to-medium fulfillment centers, post offices, and factory warehouses. Simply place the carton on the stainless steel tabletop, loop the strap over, and insert it into the feed slot; the machine automatically tensions, heat-seals, and cuts in 1.5 seconds.",
    ],
    features: [
      "External mechanical tension knob for instant adjustment without opening cabinet",
      "Low noise DC motor with automatic standby mode after 60s idle",
      "Hinged stainless steel tabletop for rapid coil replacement",
      "Locking swivel casters for effortless mobility across pack stations",
    ],
    specifications: [
      { label: "Cycle Speed", value: "1.5 seconds / strap cycle" },
      { label: "Strap Width Range", value: "6mm – 15.5mm (adjustable guides)" },
      { label: "Tension Range", value: "15 kgf – 50 kgf" },
      { label: "Table Height", value: "735mm ergonomic work height" },
      { label: "Power Consumption", value: "0.25 kW (Single Phase 220V)" },
      { label: "Machine Weight", value: "85 kg" },
    ],
    imageType: "machine-semi",
    isFeatured: false,
    relatedSlugs: ["aegis-pp-semi-automatic", "aegis-auto-pro-arch-8060"],
    inquiryPreset: "Inquiry regarding Aegis-Table Semi 740 Semi-Automatic Machine",
  },
  {
    id: "prod-8",
    slug: "aegis-power-batt-1600",
    name: "Aegis-Power Batt 1600 Battery Strapping Tool",
    brand: "Aegis-Tools",
    categorySlug: "tools-accessories",
    categoryName: "Hand Tools & Dispensers",
    machineType: "Manual / Hand Tools",
    tagline: "Cordless handheld friction-weld tool delivering 400 kgf tension with one-handed touch button operation.",
    summary:
      "Vestibulum lacinia arcu eget nulla. High-capacity 18V Li-Ion battery sealing PP and PET straps in under 3 seconds without metal seals.",
    description: [
      "Vestibulum lacinia arcu eget nulla. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.",
      "Eliminate heavy hoses, noisy air compressors, and expensive steel seals. The Aegis-Power Batt 1600 combines automatic tensioning, friction-heat welding, and precision cutting into a compact, lightweight handheld unit.",
      "Equipped with dual brushless motors and an interactive digital display for independent tension and weld-time programming.",
    ],
    features: [
      "Full digital touch-screen UI to set tension (400 - 4000N) and weld dwell time",
      "Fast 2.8-second friction weld cycle ensuring joint efficiency >80%",
      "Brushless motor system requiring zero maintenance or carbon brush changes",
      "Includes 2x 18V 4.0Ah Lithium-Ion packs and 30-minute rapid desktop charger",
    ],
    specifications: [
      { label: "Applicable Straps", value: "PET (Polyester) & PP (Polypropylene)" },
      { label: "Strap Width", value: "13mm – 16mm (Optional 19mm guide shoe)" },
      { label: "Strap Thickness", value: "0.5mm – 1.2mm" },
      { label: "Maximum Tension", value: "4,000 N (~400 kgf)" },
      { label: "Joint Type", value: "Friction Heat Weld (Seal-less)" },
      { label: "Battery Capacity", value: "18V 4.0Ah Li-Ion (Up to 450 straps per charge)" },
      { label: "Tool Weight", value: "3.8 kg (including battery)" },
    ],
    imageType: "tool-battery",
    isFeatured: true,
    relatedSlugs: ["aegis-pet-heavy-duty", "aegis-air-pneumatic-sealer", "aegis-cart-mobile-dispenser"],
    inquiryPreset: "Inquiry regarding Aegis-Power Batt 1600 Battery Strapping Tool",
  },
  {
    id: "prod-9",
    slug: "aegis-air-pneumatic-sealer",
    name: "Aegis-Air Pneumatic Strapping Tool P-28",
    brand: "Aegis-Tools",
    categorySlug: "tools-accessories",
    categoryName: "Hand Tools & Dispensers",
    machineType: "Industrial Machine",
    tagline: "Pneumatic combination tool engineered for continuous high-volume strapping of heavy industrial coils and ingots.",
    summary:
      "Integer nec odio. Praesent libero. Heavy-duty aluminum body engineered for shop-air connection delivering up to 6,000N clamping tension.",
    description: [
      "Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet.",
      "The premier choice for steel mills, aluminum extrusion plants, and heavy foundry packaging lines. Connected to standard 6-8 bar factory air, it provides unwavering tensioning consistency and ultra-durable friction weld joints.",
    ],
    features: [
      "Heavy industrial alloy casing resists drops, sparks, and metal dust",
      "Dual-piston pneumatic motor generates up to 6,000 N clamping force",
      "Ergonomic top balancer ring for suspension overhead on crane arms",
    ],
    specifications: [
      { label: "Compatible Straps", value: "PET & Heavy-Gauge PP" },
      { label: "Strap Width", value: "19mm, 25mm, 32mm" },
      { label: "Strap Thickness", value: "0.8mm – 1.35mm" },
      { label: "Operating Air Pressure", value: "0.5 – 0.8 MPa (5 – 8 bar)" },
      { label: "Max Tension", value: "6,000 N" },
      { label: "Total Weight", value: "4.9 kg" },
    ],
    imageType: "tool-pneumatic",
    isFeatured: false,
    relatedSlugs: ["aegis-pet-extreme-tensile", "aegis-power-batt-1600"],
    inquiryPreset: "Inquiry regarding Aegis-Air Pneumatic Strapping Tool P-28",
  },
  {
    id: "prod-10",
    slug: "aegis-cart-mobile-dispenser",
    name: "Aegis-Cart Heavy-Duty Mobile Strap Dispenser",
    brand: "Aegis-Tools",
    categorySlug: "tools-accessories",
    categoryName: "Hand Tools & Dispensers",
    machineType: "Accessory",
    tagline: "Ergonomic steel cart with automatic disc brake, tool tray, and universal core adaptors.",
    summary:
      "Duis sagittis ipsum. Praesent mauris. Prevents strap coil unraveling and stores ratchets, battery tools, and metal seals on wheels.",
    description: [
      "Duis sagittis ipsum. Praesent mauris. Fusce nec tellus sed augue semper porta. Mauris massa. Vestibulum lacinia arcu eget.",
      "Eliminates messy coil spillage and operator strain. Designed with a spring-actuated friction disc brake that halts rotation the instant the operator stops pulling strap, preventing loose coil tangles.",
    ],
    features: [
      "Spring disc brake prevents momentum over-spin and band tangling",
      "Universal quick-mount spindle fits both 200mm (PP) and 406mm (PET) cores",
      "Spacious all-steel front utility tray holds hand tools, seals, and cutters",
      "Heavy-duty solid rubber wheels roll easily over gravel, cracks, and ramps",
    ],
    specifications: [
      { label: "Core Diameter Support", value: "200mm & 406mm (interchangeable hubs)" },
      { label: "Max Coil Width", value: "200mm" },
      { label: "Wheel Diameter", value: "200mm heavy-duty rubber wheels" },
      { label: "Frame Material", value: "Powder-coated tubular steel" },
      { label: "Cart Weight", value: "18.5 kg" },
    ],
    imageType: "dispenser",
    isFeatured: false,
    relatedSlugs: ["aegis-pp-semi-automatic", "aegis-power-batt-1600", "aegis-tool-manual-kit"],
    inquiryPreset: "Inquiry regarding Aegis-Cart Heavy-Duty Mobile Strap Dispenser",
  },
  {
    id: "prod-11",
    slug: "aegis-tool-manual-kit",
    name: "Aegis-Tool Manual Tensioner & Sealer Kit",
    brand: "Aegis-Tools",
    categorySlug: "tools-accessories",
    categoryName: "Hand Tools & Dispensers",
    machineType: "Manual / Hand Tools",
    tagline: "Industrial forged steel ratcheting tensioner and long-handle double-notch crimp sealer set.",
    summary:
      "Mauris massa. Vestibulum lacinia arcu eget nulla. Reliable mechanical field kit for strapping pallets, crates, and bundles anywhere.",
    description: [
      "Mauris massa. Vestibulum lacinia arcu eget nulla. Class aptent taciti sociosqu ad litora torquent per conubia nostra.",
      "The classic, unbreakable tool combination for manual pallet strapping. The ratcheting tensioner easily tensions PP and PET strapping, while the compound-action crimper seals metal clips with maximum crimp retention.",
    ],
    features: [
      "Drop-forged alloy steel jaws heat treated for thousands of crimp cycles",
      "Deep serrated gripper foot grips strap firmly without pre-mature slip",
      "High leverage handles with slip-resistant vinyl comfort grips",
    ],
    specifications: [
      { label: "Set Components", value: "1x Rotary Tensioner + 1x Double-Action Sealer" },
      { label: "Compatible Straps", value: "PP & PET 12mm – 19mm" },
      { label: "Sealing Type", value: "Metal Crimp Seal / Serrated Seal" },
      { label: "Combined Weight", value: "4.2 kg" },
    ],
    imageType: "tool-manual",
    isFeatured: false,
    relatedSlugs: ["aegis-pp-manual-grade", "aegis-clamp-seals-series"],
    inquiryPreset: "Inquiry regarding Aegis-Tool Manual Tensioner & Sealer Kit",
  },
  {
    id: "prod-12",
    slug: "aegis-clamp-seals-series",
    name: "Aegis-Seal Serrated & Open Metal Seals",
    brand: "Aegis-Accessories",
    categorySlug: "tools-accessories",
    categoryName: "Hand Tools & Dispensers",
    machineType: "Accessory",
    tagline: "Galvanized high-friction steel seals engineered with internal teeth for maximal joint retention.",
    summary:
      "Class aptent taciti sociosqu ad litora. Galvanized cold-rolled steel seals providing superior grip on smooth and embossed straps.",
    description: [
      "Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Curabitur sodales ligula in libero.",
      "Manufactured from high-grade galvanized steel with precision internal teeth that bite into both strap layers upon crimping, preventing joint slippage under high tensile shock loads.",
    ],
    features: [
      "Internal serrated knurling bites deep into polymer surfaces",
      "Hot-dip zinc coating protects against outdoor corrosion and warehouse humidity",
      "Available in open-snap, closed-thread, and overlap configurations",
    ],
    specifications: [
      { label: "Material", value: "Cold-Rolled Galvanized Steel" },
      { label: "Compatible Widths", value: "13mm, 16mm, 19mm" },
      { label: "Gauge Thickness", value: "0.8mm – 1.0mm" },
      { label: "Packaging Unit", value: "1,000 pcs / carton" },
    ],
    imageType: "seal",
    isFeatured: false,
    relatedSlugs: ["aegis-tool-manual-kit", "aegis-pp-manual-grade"],
    inquiryPreset: "Inquiry regarding Aegis-Seal Serrated Metal Seals",
  },
];

